# Generated by Django 5.1.4 on 2025-01-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
    ]
